
version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    # Optional: Add depends_on if frontend needs backend to be up first
    # depends_on:
    #   - backend

  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

# Optional: Define networks or volumes here if needed
# networks:
#   default:
#     driver: bridge
volumes:
  db_data:

